# User config
author: "Tri-Co Hackathon 2019"
tagline: "wonderful wonderful static"
description: "learning static web development building blocks"
keywords: "jekyll, tutorial"
email: "digitalscholarship@swarthmore.edu"
# linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/_nabilk"
github: "https://github.com/swat-ds"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

plugins:
  - github-pages
  - pagemaster


collections:
  monuments:
    output: true
    source: monuments.csv
    id_key: pid
    layout: project